git clone https://github.com/robbiehanson/CocoaLumberjack.git
git clone https://github.com/gmoledina/GMGridView.git
git clone https://github.com/kstenerud/KSReachability.git
git clone https://github.com/lexrus/LTUpdate.git
git clone https://github.com/mattgemmell/MGImageUtilities.git
#git clone https://github.com/jverkoey/nimbus.git
git clone https://github.com/Sephiroth87/ODRefreshControl.git
git clone https://github.com/soffes/sskeychain.git
git clone https://github.com/soffes/sstoolkit.git
git clone https://github.com/samvermette/SVProgressHUD.git
git clone https://github.com/samvermette/SVWebViewController.git
git clone https://github.com/michaeltyson/TPKeyboardAvoiding.git
git clone https://github.com/vicpenap/VPPMap.git
git clone https://github.com/Inferis/ViewDeck.git
git clone https://github.com/nicklockwood/ViewUtils.git
git clone https://github.com/m1entus/WCAlertView.git
git clone https://github.com/nicklockwood/iCarousel.git
git clone https://github.com/atgreen/libffi.git