platform :ios
pod 'JSONKit' , '~> 1.4'
pod 'Reachability' ,'~> 3.0.0'
pod 'ASIHTTPRequest' 

pod 'CocoaLumberjack'
pod 'GMGridView'
pod 'KSReachability'
pod 'LTUpdate'
pod 'MGImageUtilities'
pod 'Nimbus' 
pod 'ODRefreshControl'
pod 'sskeychain'
pod 'sstoolkit'
pod 'SVProgressHUD'
pod 'SVWebViewController'
pod 'TPKeyboardAvoiding'
pod 'VPPMap'
pod 'ViewDeck'
pod 'ViewUtils'
pod 'WCAlertView'
pod 'iCarousel'
pod 'libffi'