platform :ios ,'5.0' 
pod 'JSONKit' , '~> 1.4'
pod 'Reachability' ,'~> 3.0.0'
#pod 'ASIHTTPRequest'
#pod 'MZDayPicker'
pod 'MGBox2'
pod 'ViewDeck'
#pod 'PopoverView'
pod  'MKNetworkKit'

# pod 'CocoaLumberjack'
# pod 'GMGridView'
# pod 'KSReachability'
# pod 'LTUpdate'
# pod 'MGImageUtilities'
# pod 'Nimbus' 
# pod 'ODRefreshControl'
# pod 'SSKeychain'
# pod 'SSToolkit'
# pod 'SVProgressHUD'
# pod 'SVWebViewController'
# pod 'TPKeyboardAvoiding'
# pod 'VPPMap'
# pod 'ViewUtils'
# pod 'WCAlertView'
# pod 'iCarousel'
# pod 'libffi'




